version: '3.4'
services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Admin357/
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin357/
      MYSQL_DATABASE: db_thecatapi
    ports:
      - "3308:3306"
    networks:
      - generation-network
  thecatapi:
    restart: always
    build: ./thecatapi
    working_dir: /thecatapi
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./thecatapi:/thecatapi
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - generation-network
networks:
    generation-network:
        driver: bridge